# Generated by Django 3.1.6 on 2021-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='recordinorder',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='recordinorder',
            old_name='orderId',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
